import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import SProvider from "@/components/SProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <SProvider>
      <body className="bg-gradient-to-r from-indigo-500 from-10% via-sky-500 via-30% to-emerald-500 to-90% ...">
      <Navbar/>
        {children}
      </body>
      </SProvider>
    </html>
  );
}
